# Generated by Django 3.1.1 on 2020-10-02 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('services', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('check', 'Check'), ('split', 'Split')], default='cash', max_length=5)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.schedulerappointment')),
            ],
        ),
        migrations.CreateModel(
            name='SSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('check', 'Check'), ('split', 'Split')], default='cash', max_length=5)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.schedulerappointment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='SMSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.modifier')),
                ('service_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.ssale')),
            ],
        ),
        migrations.CreateModel(
            name='PSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unitSalePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('check', 'Check'), ('split', 'Split')], default='cash', max_length=5)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.schedulerappointment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
